listen_addresses: "0.0.0.0:3000"
keep_alive: 75
worker_processes: 1

postgres:
  connection_string: ${DATABASE_URL}
  default_srid: 4326
  pool_size: 5

  tables:
    universities:
      schema: public
      table: universities
      srid: 4326
      geometry_column: geom
      geometry_type: POINT
      properties:
        name: text
        name_short: text
        address: text
        website: text
        students: int
